import Head from 'next/head'

import { Banner } from '../components/Banner'
import { Feature } from '../components/Feature'
import Pizzalist from '../components/Pizzalist'
import axios from 'axios'


import styles from '../styles/Home.module.css'


export default function Home({pizzalist}) {
  return (
    <div className={styles.container}>
     
      <Head>
        <title>Food Order App</title>
        {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"></link>
        <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Banner></Banner>
      <Pizzalist pizzalist={pizzalist}/>
      <Feature></Feature>
      
      
      
      
      
      
    </div>
  )
}



export async function getServerSideProps() {
 
  const res = await axios.get ("http://localhost:3000/api/products");
  


  return { 
    props: 
   {
     pizzalist:res.data,
   },
  };
};