import Head from 'next/head'

import { Banner } from '../components/Banner'
import { Feature } from '../components/Feature'
import Pizzalist from '../components/Pizzalist'
import axios from 'axios'


import styles from '../styles/Home.module.css'


export default function Home({pizzalist}) {
  return (
    <div className={styles.container}>
     
      <Head>
        <title>Food Order App</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Banner></Banner>
      <Pizzalist pizzalist={pizzalist}/>
      <Feature></Feature>
      
      
      
      
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      
    </div>
  )
}



export async function getServerSideProps() {
 
  const res = await axios.get ("http://localhost:3000/api/products");
  


  return { 
    props: 
   {
     pizzalist:res.data,
   },
  };
};